### ISSUE TITLE
how to run MyFirstWinRtc Sample App demo on HoloLens 2

### ISSUE THREAD

**Issue by zhuisa** [Noemata/XamlBenchmark#1]
Hi ! I was able to run MyFirstWinRtc Sample App demo successfully on both computers, one is run the demo, one is open the appr.tc web. However, I cannot run the demo on HoloLens 2 ,HoloLens 2 run the demo, one computer open the appr.tc web. HoloLens 2 does not have video. Who can tell me what's wrong. Looking forward your replaying! Good Luck!
My email address ZhuiSaDay@gmail.com.

**Comment by Noemata** [comment]
Although I am familiar with WinRtc, I am confused by your query about this here?
